### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21

### ISSUE THREAD

**Issue by dburr** [wxfnyu/magiarecord_automatic_updater#1]
Tried installing the new JP 2.3.3 APK today, and am getting the folllowing error

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

When I run the downlolader with `RUST_BACKTRACE=1` as suggested, I get the following stack trace when it crashes:

```
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic
             at src/libcore/panicking.rs:49
  11: magiarecord_automatic_updater::get_apk
  12: magiarecord_automatic_updater::main
  13: std::rt::lang_start::{{closure}}
  14: main
```

If I manually download and install the APK from the APKpure page, it works fine.

My theory is that APKpure changed the format of the download page, which is causing `magiarecord_automatic_updater` to get confused and crash.

**Comment by dburr** [comment]
Interestingly, I tried compiling the updater from source (so that I could run it under a debugger with debug symbols etc.) and... it worked?! Perhaps there was a bug in one of the dependencies which got updated? So maybe just building new executables should be sufficient?

**Comment by wxfnyu** [comment]
Hi! Sorry that it took a sec for me to respond, unfortunately the CI (Travis) i was using with this no longer supports the free compilation. If you'd like to update the binaries it would be much appreciated, but I simply don't have time at this point to do it myself.

Also please let me know if you would be interested in developing this project further, and I can transfer ownership of the repo to you.
